app:
  name: consent-to-fhir
  log-level: info
  mapper:
    consent-system: https://fhir.diz.uni-marburg.de/sid/consent-id
    patient-system: https://fhir.diz.uni-marburg.de/sid/patient-id

kafka:
  bootstrap-servers: localhost:9092
  security-protocol: ssl
  ssl:
    ca-location: /app/cert/kafka-ca.pem
    certificate-location: /app/cert/app-cert.pem
    key-location: /app/cert/app-key.pem
    key-password: private-key-password
  input-topic:
  output-topic:
  num-consumers: 1

gics:
  signer-id: "Patienten-ID"
  fhir:
    base:
    auth:
      user:
      password:
