app:
  name: consent-to-fhir
  log-level: info
  mapper:
    consent-system: https://fhir.diz.uni-marburg.de/sid/consent-id
    patient-system: https://fhir.diz.uni-marburg.de/sid/patient-id
    domain-system: https://fhir.diz.uni-marburg.de/fhir/sid/consent-domain-id
    profiles:
      - MII: https://www.medizininformatik-initiative.de/fhir/modul-consent/StructureDefinition/mii-pr-consent-einwilligung

kafka:
  bootstrap-servers: localhost:9092
  security-protocol: ssl
  ssl:
    ca-location: /app/cert/kafka-ca.pem
    certificate-location: /app/cert/app-cert.pem
    key-location: /app/cert/app-key.pem
    key-password: private-key-password
  input-topic:
  output-topic:
  num-consumers: 1

gics:
  fhir:
    base:
    auth:
      user:
      password:
